{{- if .Values.datadog.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock-event-generator-service.fullname" . }}
  labels:
    {{- include "stock-event-generator-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  datadogApiKey: {{ .Values.datadog.apiKey | quote }}
{{- end }}
