replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: stock-event-generator-service
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: stock-event-generator-service.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

datadog:
  apiKey: ""
  site: us5.datadoghq.com
  env: development

config:
  serverPort: 8081
  webhookUrl: http://stock-webhook-service:8090/v1/stock/callbacks
  tickers:
    - AAPL
    - MSFT
  intervalMs: 1000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
